# GitHub Actions workflow that automates the deployment process to a local agent on a Windows server.

name: Local Agent deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dagster Cloud CLI
        run: pip install dagster-cloud

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Dagster project to the server
        run: |
          scp -r ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/path/to/dagster/project

      - name: Add or Update Dagster Cloud Code Location
        run: |
          dagster-cloud workspace add-location test_location \
            --package-name dagster_cloud_examples \
            --api-token ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
